### ISSUE TITLE
Python3 Compatibility issues?

### ISSUE THREAD

**Issue by danhong** [Kloudless/kloudless-python#1]
Error with 

except KeyError, e:

Fixed by using 

except KeyError as e:

Occurs 2 times in resources.py.

-------

In line 778 (resources.py), dict.iteritems() is not supported. Replaced with dict.items()

-------

EDIT: Will create fork for python3 soon.

**Comment by vinodc** [comment]
Thanks! The SDK isn't compatible with Python 3 currently, but any contributions are welcome.
